app = "my-telegram-bot"
primary_region = "ams"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PYTHONUNBUFFERED = "1"

[processes]
  app = "python bot.py"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  processes = ["app"]
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    handlers = ["http"]
    port = 8080

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = 30000
    timeout = 10000
    grace_period = "10s"
    method = "get"
    path = "/health"
